CodeitFS5th-middle-project-team1/DocThru-FE

.github/workflows/auto-assign.yml, .github/workflows/pr-open-add-project-in-InReview.yml
- 이슈와 PR을 생성하면 자동으로 담당자가 정해집니다.
- PR을 생성하면 자동으로 Project에 In Review 상태가 갑니다.
=> docs: github action 자동화 스크립트 생성

src/app/layout.tsx, src/app/main/challenge/[id]/edit/page.tsx, src/app/main/challenge/layout.tsx, src/app/main/challenge/new/page.tsx, src/shared/components/form/ChallengeForm.tsx
- 생성/ 수정 페이지 UI 구현
- Form컴포넌트를 따로 만들어서 구현
- 각 페이지 구현 완료
- X
- X
- 신규 챌린지 생성 페이지
- 신규 챌린지 Data 예시 (콘솔 사용)
- 수정 페이지
-수정 Data 예시 (콘솔 사용)
=> 생성/ 수정 페이지 UI 구현 완료

src/app/main/my-challenge/components/ChallengeTable.tsx, src/app/main/my-challenge/page.tsx, src/shared/components/dropdown/Sort.tsx, src/shared/components/input/search.tsx, src/stories/Chip.stories.ts
- 나의 챌린지 중 신청한 챌린지 탭 페이지 UI 1차적으로 구현하였습니다. 
- /main/my-challenge
- ChallengeTable 컴포넌트 파일 생성해서 작업했습니다.
- 스토리북으로 작업을 잘 해주셔서 잘 가져와서 사용할 수 있었습니다. 👍 (디테일적으로 수정이 필요할 것 같은 부분은 아래 스크린샷 첨부했습니다.)
- 테이블 헤더 모든 모서리에 라운드를 주기 위해서 헤더만 div로 분리시키고 테이블바디는 테이블로 분리시켰더니 반응형 구현시 헤더와 테이블이 따로 놀게되어서 헤더와 테이블 각 컬럼에 동일하게 flex를 적용했습니다. 더 좋은 방법이 있다면 알려주세요 프론트 고수님들 ~!
- 아직 API 연결하지 않아서 목데이터 상태입니다.
- chip 높이 여백 (py) 추가해주시면 좋을 것 같습니다.
- 드롭다운 필터 적용하였습니다.
- #44
=> [UI] 나의 챌린지 - 신청한 챌린지 

package-lock.json, package.json, src/app/main/my-challenge/[id]/components/cardDetail.tsx, src/app/main/my-challenge/[id]/components/mock.ts, src/app/main/my-challenge/[id]/components/status.tsx, src/app/main/my-challenge/[id]/page.tsx, src/shared/components/input/index.tsx, src/shared/components/input/text.tsx, src/types.ts, yarn.lock
- 나의 챌린지 페이지 1차 구현 완료 했습니다
- input text  리팩토링 진행 했습니다
- input text  error 메세지랑 error 규칙 추가
- api가 아직 미완성이라 mock데이터를 넣어서 진행하였습니다
- input text부분에 희성님 요청으로 error 메세지랑 error 규칙을 넣을 수 있게 추가 되었습니다
- 아래 보기와 같이 넣어주시면 됩니다
-<textarea
name="description"
register={register}
rules={{ required: '내용을 입력해주세요.' }}
errorMessage={errors.description?.message}
/>
- #11
=> feat: 나의 챌린지 페이지 - 신청한 챌린지- 상세(삭제, 대기,  거절)

src/app/main/challenge/[id]/components/Title.tsx, src/app/main/challenge/[id]/edit/page.tsx, src/app/main/challenge/[id]/page.tsx, src/app/main/challenge/_components/Pagination.tsx, src/app/main/my-challenge/[id]/components/mock.ts, src/shared/components/CheckBox.tsx, src/shared/components/RadioBtn.tsx, src/shared/components/Reply.tsx, src/shared/components/card/Card.tsx, src/shared/components/chip/chip.tsx, src/shared/components/dropdown/Filter.tsx, src/shared/components/form/AuthForm.tsx, src/shared/components/form/ChallengeForm.tsx, src/shared/components/input/date.tsx, src/shared/components/input/email.tsx, src/shared/components/input/password.tsx, src/shared/components/input/search.tsx, src/shared/components/input/text.tsx, src/types.ts
=> fix: 타입 및 오류 수정

src/api/AuthApi.ts, src/api/ChallengeApi.ts, src/api/FeedBackApi.ts, src/api/TransLationApi.ts, src/api/store/AuthStore.ts, src/api/store/ChallengeStore.ts, src/api/store/FeedBackStore.ts, src/api/store/translationStore.ts, src/api/url.ts, src/app/main/challenge/[id]/components/ListItems.tsx, src/app/main/challenge/[id]/components/Participation.tsx, src/app/main/challenge/[id]/components/Title.tsx, src/app/main/challenge/[id]/page.tsx, src/app/main/challenge/_components/ChallengeMain.tsx, src/app/main/translation/[id]/_components/Author.tsx, src/app/main/translation/[id]/_components/FeedBack.tsx, src/app/main/translation/[id]/_components/Title.tsx, src/app/main/translation/[id]/page.tsx, src/constants.ts, src/lib/api/auth.ts, src/lib/api/axiosInstance.ts, src/lib/api/challenge.ts, src/shared/components/Reply.tsx, src/shared/components/card/Card.tsx, src/shared/components/chip/chip.tsx, src/shared/components/dropdown/Filter.tsx, src/shared/components/layout/Header.tsx, src/shared/components/layout/Layout.tsx, src/shared/components/layout/core.ts, src/types.ts
- 
- 일단 페이지 돌아 가게끔 해 둿고 api 일부 연결 해뒀습니다. 
- 디테일 한건 우선 나뒀습니다.
- 일단 페이지 이동은 될겁니다. 
- 
API 하나의 폴더에 다 정리 해 둿고 우선 zustand 만 사용 해서 sotre 만들어서 저장 해서 사용 하도록 해뒀습니다.
API 일단 다 포트가 다를 지도 모르니 .env에 
NEXT_PUBLIC_API_URL=http://localhost:5000/api 
넣고 본인 local 백엔드 포트 넣어 주시면 될겁니다.
- 
- 
-
=> 54 feature api create

src/app/layout.tsx, src/app/main/translation-work/[id]/page.tsx, src/app/main/translation-work/_components/Editor.tsx, src/app/main/translation-work/page.tsx, src/shared/components/container/Container.tsx, src/types.ts
- 작업물 생성 API 테스트 (오류 메시지 모달 추가)
- 로컬 스토리지에 있는 challengeId로 값을 가져와서 POST API에 사용했습니다.
- 임시 저장 후, 임시 저장한 데이터를 불러와 에디터에 반영까지 테스트 했습니다.
- 아직 생성 부분만 테스트를 완료해서 중간 PR 올립니다.
- #58 
-
=> [Feature] 작업물 생성, 임시저장, 임시저장 불러오기 테스트

src/app/layout.tsx, src/app/main/translation-work/[id]/page.tsx, src/app/main/translation-work/_components/Editor.tsx, src/app/main/translation-work/page.tsx
- 챌린지 작업 헤더 제거, placeholder 추가
- 헤더 제거, 상위 div에 반응형 적용, placeholder 추가
- 
#56
-
=> fix: 챌린지 작업 헤더 제거, placeholder 추가

src/app/main/translation-work/[id]/page.tsx, src/app/main/translation-work/page.tsx, src/shared/components/modal/confirm.tsx, src/types.ts
- 수정 및 생성 페이지 코드를 1차적으로 수정했습니다. (이후 작업을 위해 한번 더 리팩토링을 거쳐 컴포넌트 분리 해야합니다.)
- 에러 처리, useState 합치기 작업
- 
- 
-
=> fix: 1차 코드 리팩토링

src/api/auth/AuthStore.ts, src/api/challenge/ChallengeApi.ts, src/api/challenge/ChallengeHooks.ts, src/app/main/challenge/_components/ChallengeHead.tsx, src/app/main/challenge/_components/ChallengeMain.tsx, src/app/main/my-challenge/components/MyChallengeHead.tsx, src/app/main/my-challenge/components/MyChallengeMain.tsx, src/shared/components/card/Card.tsx, src/shared/components/dropdown/Filter.tsx, src/shared/components/dropdown/ProfileDropdown.tsx
- 챌린지 목록 API연결 및 필터 연결
- 나의 챌린지 API연결
- 헤더 나의 챌린지 항목 추가 및 경로 연결
- 담당 페이지 맞는 API연결 완료 했습니다.
- 헤더의 추가된 나의 챌린지 항목클릭시 my-challenge경로로 이동됩니다.
- 
- 
-
=> 챌린지 목록 API연결, 나의 챌린지 API연결, 헤더 드롭다운 수정

src/api/challenge/ChallengeApi.ts, src/api/challenge/ChallengeHooks.ts, src/app/admin/challenges/[id]/components/cardDetail.tsx, src/app/admin/challenges/[id]/components/index.tsx, src/app/admin/challenges/[id]/components/nav.tsx, src/app/admin/challenges/[id]/components/status.tsx, src/app/admin/challenges/[id]/components/statusBottom.tsx, src/app/main/my-challenge/[id]/components/cardDetail.tsx, src/app/main/my-challenge/[id]/components/index.tsx, src/app/main/my-challenge/[id]/components/status.tsx, src/app/main/my-challenge/components/MyChallengeMain.tsx, src/shared/Img/arrow-icon/no-stick/icon_arrow_left.svg, src/shared/Img/arrow-icon/no-stick/icon_arrow_right.svg
- 오류 수정 완료 하였습니다
- 추후에 리팩토링 진행하겠습니다 
- 제가 쓴 console.log 지웠습니다
- mock 데이터가 아닌 실제 api로 해두었습니다
- 들어가는 url은 이렇게 2개 있습니다
main/my-challenge/id
admin/challenges/id
- #11 
스크린샷을 보면 my-challenge에서 누른 게시글 상세보기가 challenge로 가고 있습니다 이건 노션에도 작성해 두겠습니다
=> fix: 타입 및 오류 수정 완료

src/api/Translation/api.ts, src/api/Translation/hook.ts, src/app/main/translation-work/[id]/page.tsx, src/app/main/translation-work/_components/PatchCard.tsx, src/app/main/translation-work/_components/PostCard.tsx, src/app/main/translation-work/page.tsx
- 번역물 수정 및 삭제 에러 해결 및 쿼리 데이터 기준으로 challengeId 받아오기
- challengeId를 쿼리로 받아옵니다. (ex: ?challengeId=...)
- challengeId를 쿼리로 받아옵니다. (ex: ?challengeId=...)
- 따라서 번역물 수정이나 생성 페이지로 넘어오는 경우 challengeId를 쿼리에 넣어서 링크 걸어주셔야 합니다.
- useToast 쓰려다가 오류 핸들링이 안되어서 useMutation으로 수정했습니다. (임시저장 제외)
- #100 
npm run build 했을 때 스토리북 오류 나는 거 같은데 괜찮으면 머지 하려고 합니다!
=> 머지X 에러가 하나 있는데 물어보고 머지하려고 합니다.

src/api/admin/admin.ts, src/api/notification/notification.api.ts
- api 파일 경로를 이동한 것들이 이전 PR에서 누락되었던 것 같습니다. 파일들 다시 추가해서 올립니다 !
=> 경로이동된 api 파일 복구

src/api/Translation/api.ts, src/api/auth/AuthApi.ts, src/api/challenge/ChallengeApi.ts, src/api/feedback/api.ts, src/api/feedback/hook.ts, src/api/url.ts, src/lib/utill.ts
- 
axios fetch로 변경 
api만 바뀌어서 기존 hook은 그대로 사용 하셔도 됩니다.
- 
- 
- 
-
=> Fix : axios 형식 fetch로 변경

src/api/challenge/ChallengeApi.ts, src/api/challenge/ChallengeHooks.ts, src/app/admin/challenges/[id]/components/statusBottom.tsx, src/app/main/my-challenge/[id]/components/cardDetail.tsx, src/shared/components/form/ChallengeForm.tsx, src/shared/components/input/text.tsx
- 상세페이지 실시간 값을 받아오기 위해 커스텀 훅을 만들었습니다
- ChallengeHooks.ts에 커스텀 훅을 만들었습니다
- input textarea부분 수정 완료 했습니다
- 상세페이지에서 승인이나 거절을 누르면 
- 
-
=> Refactor: 상세보기페이지 커스텀 훅

src/api/Translation/api.ts, src/api/Translation/hook.ts, src/api/challenge/ChallengeHooks.ts, src/api/feedback/hook.ts, src/api/like/api.ts, src/api/like/hook.ts, src/app/main/challenge/[id]/components/ListItems.tsx, src/app/main/challenge/[id]/components/Participation.tsx, src/app/main/challenge/[id]/components/Title.tsx, src/app/main/challenge/[id]/page.tsx, src/app/main/translation-work/[id]/page.tsx, src/app/main/translation-work/_components/PatchCard.tsx, src/app/main/translation-work/_components/PostCard.tsx, src/app/main/translation-work/_components/PostMain.tsx, src/app/main/translation/[id]/_components/Author.tsx, src/app/main/translation/[id]/_components/FeedBack.tsx, src/app/main/translation/[id]/page.tsx, src/shared/components/Reply.tsx, src/shared/components/card/Card.tsx, src/shared/components/chip/chip.tsx, src/shared/components/container/Container.tsx
- 
작업물생성 페이지 오류 해결 
api 호출 하여 목록 불러오는 api 호출시 id값이 없을때 호출 되지 않는 옵션 추가 
번역물쪽 page의 url에 쿼리스트링으로 id값 반환  
- 
지금 res에서 401에러면 로그아웃 되는데 이건 backend랑 오류 타입 수정 해서 토큰 만료 됬을때만 되거나 하는게 좋을거 같아 보입니다.
- 
- 
-
=> Fix : 작업물 페이지 오류 해결 및 기타사항 수정

src/api/url.ts
=> vercel api경로 상대 경로로 변경

src/api/auth/AuthHook.ts, src/api/url.ts, src/app/_components/ClientLayout.tsx, src/app/layout.tsx
- 쿠키에 갱신한 에세스 토큰까지 넣어서 보내는 것 추가
- 
- 
- 
-
=> document.cookie 추가

src/api/url.ts, src/middleware.ts
- 미들웨어 토큰 확인방식 디코딩 변경
- 토큰 검증은 서버에서 이루어지니 프론트 미들웨어는 있는것만 확인하는게 맞다고 생각함
1. 토큰 확인 방식을 디코딩으로 변경
2.  토큰을 위조하더라도 백엔드에서 검증 됨
- X
- X
- X
=> 미들웨어 토큰 확인방식 수정

src/api/challenge/ChallengeApi.ts, src/api/challenge/ChallengeHooks.ts, src/app/main/challenge/[id]/page.tsx, src/app/main/translation/[id]/_components/Title.tsx
- 
- 
const {data} = useGetChallengeByAdmin( 여기에 params 넣고 ) 이렇게 불러서 쓰시면 될거 같습니다.
- 
- 
-
=> Feat : challenge 관리자 목록 불러오기 api 훅 추가

src/api/Translation/hook.ts, src/api/challenge/ChallengeHooks.ts, src/api/feedback/hook.ts, src/app/main/challenge/[id]/page.tsx, src/app/main/translation-work/_components/PostCard.tsx, src/app/main/translation/[id]/_components/Title.tsx, src/shared/components/container/Container.tsx
- 
번역물 생성 본문 2000자 제목 50제한 으로 수정 
api호출시 캐싱 추가 
번역물 삭제 후 잔여 데이터로 api에러 발생하여 수정 했습니다.
- 
- 
- 
-
=> 142 bug fix

src/app/_components/ClientLayout.tsx, src/app/admin/challenges/[id]/components/index.tsx, src/app/layout.tsx, src/app/loading.tsx, src/app/main/my-challenge/[id]/components/index.tsx, src/app/main/translation-work/[id]/page.tsx, src/app/main/translation-work/_components/PatchMain.tsx, src/app/main/translation-work/_components/PostMain.tsx, src/app/main/translation-work/page.tsx, src/core/provider/AuthProvider.tsx, src/shared/components/AnimateLoad.tsx
- 간단한 로딩 페이지 입니다
- Suspense로 감싸져 있는 것들이랑 로딩에 토스트가 잘 나오게 수정 완료 했습니다 확인 부탁드립니다
- 1.5초 동안 나오게 수정했습니다
- 
-
=> feat: 로딩 페이지
